### ISSUE TITLE
Downloading assets

### ISSUE THREAD

**Issue by MoskalykA** [Snowiiii/Vent-Engine#16]
Hello,
the download of the assets has no instructions, how can we do?

**Comment by Snowiiii** [comment]
Hey, haven't heard from you in a while, The Assets are currently inside the crates so there should be no Problems or Erros

**Comment by MoskalykA** [comment]
```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Import("Unable to open file \"E:\\Github\\Vent-Engine\\crates\\vent-runtime/assets/models/test/Sponza/sponza.obj\".")', E:\Github\Vent-Engine\crates\vent-common\src\render\model\model_loader.rs:25:10```

I can't download the assets

**Comment by Snowiiii** [comment]
> `` thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Import("Unable to open file \"E:\\Github\\Vent-Engine\\crates\\vent-runtime/assets/models/test/Sponza/sponza.obj\".")', E:\Github\Vent-Engine\crates\vent-common\src\render\model\model_loader.rs:25:10 ``
> 
> I can't download the assets

Upsi Unix File Seperator, Ye ah the Code is in a really hard development the The Error should be gone if your replace ```/``` to ```\\``` how its in the other Paths behind, The Model will be currently test loaded in app_renderer

**Comment by MoskalykA** [comment]
> > `` thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Import("Unable to open file \"E:\\Github\\Vent-Engine\\crates\\vent-runtime/assets/models/test/Sponza/sponza.obj\".")', E:\Github\Vent-Engine\crates\vent-common\src\render\model\model_loader.rs:25:10 ``
> > I can't download the assets
> 
> Upsi Unix File Seperator, Ye ah the Code is in a really hard development the The Error should be gone if your replace `/` to `\\` how its in the other Paths behind, The Model will be currently test loaded in app_renderer

The folder where the 3D model should be is just empty

**Comment by Snowiiii** [comment]
Ye, Dont like for some reason that i put in models :c just put in this https://github.com/jimmiebergmann/Sponza

**Comment by Snowiiii** [comment]
But be warned that Model Loading is not really working because i fucked up with parsing
