### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by MoskalykA** [Snowiiii/Vent-Engine#18]
**Is your feature request related to a problem? Please describe.**
My request is not really a problem but I will describe it, the workflows are executed following a pull request, during the execution of these workflows there are tests on the correct functioning of the proposed code. However if the modified elements do not include any modification of the Rust code there will still be these workflows which are clearly not necessary anymore since the modified elements have nothing to do with the Rust code

**Describe the solution you'd like**
I propose to impose labels for pull requests (e.g. rust, docs, etc) to be able to adapt the workflows. So if a pull request has the label docs then the rust workflow does not run.

**Describe alternatives you've considered**
If the labels are not suitable, we could see if it is possible to look at the extensions present in a pull request

**Additional context**
[I have already seen this for label detection in a pull request from a workflow](https://stackoverflow.com/questions/62325286/run-github-actions-when-pull-requests-have-a-specific-label)

**Comment by Snowiiii** [comment]
Thank you for the suggestion, I have implemented it successfully!
