### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by MoskalykA** [Snowiiii/Vent-Engine#3]
Hi,
I get these errors when compiling
[error.txt](https://github.com/Snowiiii/Vent-Engine/files/10888045/error.txt)

**Comment by Snowiiii** [comment]
Hey, Yes its my bad currently there are some Erros i pushed in, Nothing big i guess i can Fix this Quickly

**Comment by MoskalykA** [comment]
The error is fixed, perfect 👍🏻
